# Generated by Django 5.0.4 on 2024-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pImage',
            field=models.URLField(),
        ),
    ]
