# Generated by Django 5.0.4 on 2024-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_drinks_rolls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price10', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name_set', models.CharField(max_length=120)),
                ('price_set', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rImage', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
        migrations.DeleteModel(
            name='Rolls',
        ),
    ]
