# Generated by Django 5.0.4 on 2024-04-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_roll_rename_drinks_drink_delete_rolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='name_set',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='price_set',
        ),
    ]
